enableGitInfo = true
baseURL = "https://deng34.github.io/"
languageCode = "en-us"
title = "Deng Peng"
footnotereturnlinkcontents = "↩"
enableRobotsTXT = true
# enableGitInfo = true

[security]
  [security.http]
    urls = ['https://embed.gettyimages.com/*']

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[permalinks]
cn = "/cn/:year/:month/:day/:slug/"
en = "/en/:year/:month/:day/:slug/"
posts = "/posts/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Research"
    url = "/research/"    
    weight = 2
[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
[[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 4
[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[params]
    description = "Peronal website of Your Name"
    homeText = "You just need a Hugo blog from scratch"
    # Please make sure `blogDirNmae` matches the name used in `menu` above:
    blogDirName = "posts"
    # singleLang = true
    defaultLang = "en"
    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs" 
    MathJaxVersion = "2.7.5"
    favicon = "media/hugo-logo.png"
    # Edit by yourself:
    GithubEdit = "https://github.com/deng34/deng34.github.io/edit/main/content/"
    copyright = "&copy;"
    copyrightYear = "2024"
    # Edit by yourself:
    GithubRepo = "https://github.com/deng34/deng34.github.io"
    # Edit by yourself:
    ContentSource = "https://raw.githubusercontent.com/deng34/deng34.github.io/main/content/" 

[params.utterances]
  repo = "deng34/deng34.github.io"
  issueTerm = "pathname"
  theme = "github-light"

[params.logo]
  # Change the logo picture as your prefer:
  url = "media/my-logo.png" # you can change it
  width = 50.0
  height = 50.0
  alt = "DP"

[params.lang]

    [params.lang.author]
      en = "Peng Deng"
      cn = "邓鹏"

    [params.lang.madeWith]
      en = "Made with"
      cn = "本站驱动"

    [params.lang.edit]
      en = "Suggest an edit of this page"
      cn = "编辑本页"

    [params.lang.lastupdate]
      en = "Last modified on"
      cn = "最后一次修改于"

    [params.lang.Sitelastupdate]
      en = "Site last updated on"
      cn = "最近一次更新于"

    [params.lang.sourceCode]
      en = "Content in"
      cn = "内容存于"

    [params.lang.license]
      en = "License"
      cn = "版权"

[markup]
 defaultMarkdownHandler = "goldmark"

  [markup.goldmark]

    [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = false
    strikethrough = true
    table = true
    taskList = true
    typographer = true

    [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true

    [markup.goldmark.renderer]
    hardWraps = false
    unsafe = true
    xHTML = false
  
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pygments"
    tabWidth = 4

  [markup.tableOfContents]
  endLevel = 3
  ordered = true
  startLevel = 2

[imaging]
quality = 100